# encoding: utf-8
"""
@author     Alexander Rüedlinger <a.rueedlinger@gmail.com>
@date       17.06.2015

"""

from helper import OutputPrinter
from xwot.compiler.frontend import visitor
from xwot.compiler.backend.FlaskBackendBuilder import FlaskBackendBuilder


class FlaskHydraBackendBuilder(FlaskBackendBuilder):
    def __init__(self):
        visitor.BaseVisitor.__init__(self)
        self._out = OutputPrinter()

    def before(self):
        self._out.code([
                           '#',
                           '# Generated by xwot compiler.',
                           '#',
                           '# Flask xwot application.',
                           '#',
                           '',
                           'import os',
                           'from yadp.device import Description',
                           '',
                           'from xwot.util import local_ip',
                           'from xwot.util import create_description',
                           'from xwot.util.flask import hydra_link',
                           'from xwot.util.annotator import Annotator',
                           'from xwot.util import dir_path',
                           'from xwot.util import parent_dir_path',
                           'from xwot.util.vocabbuilder import HydraVocabBuilder',
                           '',
                           '',
                           '# base config',
                           'ip = local_ip()',
                           'port = 5000',
                           'http_addr = "http://%s:%s/" % (ip, port)',
                           'module_dir_path = dir_path(__file__)',
                           'app_dir_path = parent_dir_path(__file__)',
                           'xwot_file = os.path.join(app_dir_path, "device.xwot")',
                           '',
                           'iri = "%s%s" % (http_addr, "vocab")',
                           'vocab_url = iri + "#"',
                           'link = hydra_link(iri)',
                           '',
                           'annotator = Annotator()',
                           'vocabbuilder = HydraVocabBuilder(annotator)',
                           '',
                           'jsonld_description_str = create_description(xwot_file=xwot_file, base=http_addr)',
                           'yadp_description = Description(content_type="application/ld+json", content=jsonld_description_str)',
                           '',
                           '',
                           'from flask import Flask',
                           'from flask.ext.twisted import Twisted',
                           '',
                           'app = Flask(__name__)',
                           'Twisted(app)',
                           '',
                           ''
                           ], ["xwot_app", "__init__"])

    def after(self):
        self._out.code([
                           "import %s" % node.name() for node in self._nodes
                       ], ["xwot_app", "__init__"])

        self._out.code([
                           '#',
                           '# Generated by xwot compiler.',
                           '#',
                           '# Flask xwot application.',
                           '#',
                           '',
                           'import xwot_app',
                           'from xwot_app import app',
                           'from xwot.util.flask import mount_vocab',
                           '',
                           'import yadp',
                           'yadp.debug()',
                           '',
                           'from yadp import service',
                           'from yadp.device import Device',
                           '',
                           "device = Device(urn='urn:xwot:Device', url=xwot_app.http_addr, descriptions=[xwot_app.yadp_description])",
                           '',
                           'service = service()',
                           'service.register(device=device, passive=True)',
                           '',
                           "",
                           "if __name__ == '__main__':",
                           self._out.indent([
                               'mount_vocab(app, xwot_app.vocabbuilder)',
                               "app.run(host='0.0.0.0', port=xwot_app.port, debug=True)"
                           ])
                       ], ['runserver'])

        #